### ISSUE TITLE
请问我换ijkplayer后播放视频为什么会只有声音没有图像的

### ISSUE THREAD

**Issue by supercwn** [maning0303/MNVideoPlayer#1]
请问我换ijkplayer后播放视频为什么会只有声音没有图像的

**Comment by puyafeng** [comment]
我用ijkplayer或者基于ijk的jiechaoVideoview播放不了的视频，这个MNVideoPlayer竟然可以播，关键他也是基于ijk的啊，晕

**Comment by maning0303** [comment]
不好意思啊 ，今天刚看到，ijkplayer 这个我没有试过，视频这块我是个菜鸟，可能没办法回答你，不好意思。
