### ISSUE TITLE
画面有点拉伸

### ISSUE THREAD

**Issue by shaodong2528** [maning0303/MNVideoPlayer#3]
如果你用个微信视频或手机里拍照里面的视频来播放会发现画面出现拉伸，能否实现像jiecaovideoplayer那样画面可横可竖，但内容显示正常

**Comment by maning0303** [comment]
谢谢你的反馈，我下一版本会适配这个问题

**Comment by maning0303** [comment]
你可以试试最新版本！问题已经改好了
