### ISSUE TITLE
支持CoordinatorLayout、AppBarLayout、CollapsingToolbarLayout布局吗？

### ISSUE THREAD

**Issue by LongAgoLong** [maning0303/MNVideoPlayer#4]
支持CoordinatorLayout、AppBarLayout、CollapsingToolbarLayout布局吗？用过其他的一用就崩了，貌似都是强行把context转为activity对象导致的

**Comment by maning0303** [comment]
这个不太清楚呢，还没有尝试过，你可以试试！
