### ISSUE TITLE
如何监听全屏？

### ISSUE THREAD

**Issue by xinshengBoy** [maning0303/MNVideoPlayer#6]
通过view.getMediaPlayer()得到的mediaplayer为null，这样根本监听不了全屏和竖屏的改变呀，求楼主指点

**Comment by xinshengBoy** [comment]
因为横竖屏的切换要显示和隐藏一些东西，而已原来竖屏的时候在播放视频，切换全屏的时候已经要继续播放，而不是停止播放；而且初始化的时候点击视频播放空白页面的话控制栏最好显示；全屏返回的时候会退出整个页面，即使代码有做控制。

**Comment by maning0303** [comment]
@zhongzhihuashanghai 不好意思，刚刚看到，view.getMediaPlayer()得到的mediaplayer应该是在sufaceView创建后才能拿到的；监听全屏和竖屏这个确实没有写，下次加上！

**Comment by maning0303** [comment]
@zhongzhihuashanghai 全屏返回会退出整个页面？
`
@Override
    public void onBackPressed() {
        if (mnViderPlayer.isFullScreen()) {
            mnViderPlayer.setOrientationPortrait();
            return;
        }
        super.onBackPressed();
    }
`
Activity加上这个了吗？ 你Debug看看日志！

**Comment by maning0303** [comment]
@zhongzhihuashanghai  新版本已经可以监听横竖屏了，你看看！你那边Demo工程跑起来切换全屏也有问题吗 ？

**Comment by Cashdispenser** [comment]
确实可以监听横竖屏了，但是切换横屏的时候播放器就重新初始化了，这个希望优化一下
