### ISSUE TITLE
我的突然第一次播放不能出画面了，显示播放器初始化失败？是按照demo里面写的，之前一直可以，就今天我尝试在下载成功之后自动播放，然后就出现这个问题，代码再回复到之前也是不行了。

### ISSUE THREAD

**Issue by yaozhengzheng** [maning0303/MNVideoPlayer#9]
我的突然第一次播放不能出画面了，显示播放器初始化失败？是按照demo里面写的，之前一直可以，就今天我尝试在下载成功之后自动播放，然后就出现这个问题，代码再回复到之前也是不行了。

**Comment by maning0303** [comment]
@yaozhengzheng Demo里面可以播放吗 ？

**Comment by yaozhengzheng** [comment]
搞好了。。。。。




------------------ 原始邮件 ------------------
发件人: "马宁"<notifications@github.com>; 
发送时间: 2019年8月28日(星期三) 晚上6:25
收件人: "maning0303/MNVideoPlayer"<MNVideoPlayer@noreply.github.com>; 
抄送: "清欢"<1624566366@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [maning0303/MNVideoPlayer] 我的突然第一次播放不能出画面了，显示播放器初始化失败？是按照demo里面写的，之前一直可以，就今天我尝试在下载成功之后自动播放，然后就出现这个问题，代码再回复到之前也是不行了。 (#9)




@yaozhengzheng Demo里面可以播放吗 ？

**Comment by maning0303** [comment]
@yaozhengzheng 好了就可以，那我就暂时关掉这个了，有什么问题在反馈。感谢。
